### ISSUE TITLE
Header parameters are not generated according to swagger spec

### ISSUE THREAD

**Issue by prasannakumar1989** [infinum/dox#64]
Thank you for this amazing gem!

The schema option need to be added for header parameters. According to open api 3.0.0, headers should have a schema property. 

```
...
paths:
  /post:
    post:
      parameters:
        - in: header
          name: X-username
          schema:
            type: string
            example: user12345
```            

Currently headers don't have schema property. 

```
paths:
  /post:
    post:
      parameters:
        - in: header
          name: X-username
          example: user12345
```

Can you please address this issue ?
